### ISSUE TITLE
登陆页面的标题错误

### ISSUE THREAD

**Issue by zhihaofans** [wsdzl/acmsg#1]
标题显示为`登陆 - <?echo SITENAME;?>`
请修复

![图片](https://ooo.0o0.ooo/2016/11/05/581de812f2121.png)

**Comment by zhihaofans** [comment]
注册页面则显示`注册 - <?echo SITENAME;?>`

**Comment by zhihaofans** [comment]
是主题id：1会这样

**Comment by wsdzl** [comment]
嗯嗯嗯。少了个php标签。。。
